### ISSUE TITLE
Handle special character in parameters

### ISSUE THREAD

**Issue by simonsavoca** [simonsavoca/partyz#13]
Error:
```
URIError: Failed to decode param 'r%E9mi'
    at decodeURIComponent (<anonymous>)
    at decode_param (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:148:15)
    at matchLayer (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:574:18)
    at next (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:220:15)
    at compression (/home/simon/.node-red/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/local/lib/node_modules/node-red/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
    at query (/usr/local/lib/node_modules/node-red/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
```

Reproduce:

- Type a name with accent on login page, ex: Rémi 
- URL: /partyz/upload/21022020/r%E9mi

**Comment by simonsavoca** [comment]
Check around JSONata expression and the $decodeUrl function.
